[project]
name = "itten"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.1",
    "pillow>=12.1.0",
    "pytest>=9.0.2",
    "scipy>=1.17.0",
    "torch>=2.10.0",
    "trio>=0.32.0",
]
